/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import main.RequestManager;
import model.PlayerCharacter;

/**
 *
 * @author Florentijn
 */
public class AddCharacters extends javax.swing.JFrame {

    private ArrayList<PlayerCharacter> characters;
    private RequestManager rm;
    private DefaultListModel myCharacters = new DefaultListModel();
    private final String NO_MATCHES = "no matches were found";
    /**
     * Creates new form AddCharacters
     */
    public AddCharacters() {
        initComponents();
        liMyCharacters.setModel(myCharacters);
        populateList();
    }
    
    public void populateList() {
        rm = new RequestManager();
        characters = rm.getMyCharacters();
        if (characters.isEmpty()) {
            myCharacters.removeAllElements();
            myCharacters.addElement(NO_MATCHES);
        } else {
            myCharacters.removeAllElements();
            for (PlayerCharacter character : characters) {
                myCharacters.addElement(character);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        liMyCharacters = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        tfMyCharacters = new javax.swing.JTextField();
        btSearchMyCharacters = new javax.swing.JButton();
        btAddCharacterToEpisode = new javax.swing.JButton();
        btAddCharacterToEpisode1 = new javax.swing.JButton();
        imgCampaign2 = new javax.swing.JLabel();
        lblEpisodeDescription1 = new javax.swing.JLabel();
        lblCharacterClass = new javax.swing.JLabel();
        lblCharacterName = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblCharacterLevel = new javax.swing.JLabel();
        lblCharacterClass1 = new javax.swing.JLabel();
        lblCharacterClass2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(516, 260));
        jPanel1.setMinimumSize(new java.awt.Dimension(516, 260));

        jPanel2.setBackground(new java.awt.Color(66, 66, 66));
        jPanel2.setMinimumSize(new java.awt.Dimension(220, 159));

        jScrollPane2.setBackground(new java.awt.Color(66, 66, 66));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(66, 66, 66));

        liMyCharacters.setBackground(new java.awt.Color(66, 66, 66));
        liMyCharacters.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        liMyCharacters.setForeground(new java.awt.Color(204, 204, 204));
        liMyCharacters.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "kaas", "panda" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        liMyCharacters.setSelectionBackground(new java.awt.Color(255, 127, 0));
        liMyCharacters.setSelectionForeground(new java.awt.Color(40, 40, 40));
        liMyCharacters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liMyCharactersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(liMyCharacters);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        tfMyCharacters.setBackground(new java.awt.Color(102, 102, 102));
        tfMyCharacters.setForeground(new java.awt.Color(255, 255, 255));
        tfMyCharacters.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfMyCharacters.setBorder(null);
        tfMyCharacters.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMyCharactersKeyPressed(evt);
            }
        });

        btSearchMyCharacters.setBackground(new java.awt.Color(102, 102, 102));
        btSearchMyCharacters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_icon.png"))); // NOI18N
        btSearchMyCharacters.setBorder(null);
        btSearchMyCharacters.setBorderPainted(false);
        btSearchMyCharacters.setFocusPainted(false);
        btSearchMyCharacters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchMyCharactersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(tfMyCharacters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSearchMyCharacters, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(tfMyCharacters, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btSearchMyCharacters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
        );

        btAddCharacterToEpisode.setBackground(new java.awt.Color(66, 66, 66));
        btAddCharacterToEpisode.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btAddCharacterToEpisode.setForeground(new java.awt.Color(255, 255, 255));
        btAddCharacterToEpisode.setText("Cancel");
        btAddCharacterToEpisode.setBorder(null);
        btAddCharacterToEpisode.setBorderPainted(false);
        btAddCharacterToEpisode.setRequestFocusEnabled(false);
        btAddCharacterToEpisode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddCharacterToEpisodeActionPerformed(evt);
            }
        });

        btAddCharacterToEpisode1.setBackground(new java.awt.Color(66, 66, 66));
        btAddCharacterToEpisode1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btAddCharacterToEpisode1.setForeground(new java.awt.Color(255, 255, 255));
        btAddCharacterToEpisode1.setText("Add your character");
        btAddCharacterToEpisode1.setBorder(null);
        btAddCharacterToEpisode1.setBorderPainted(false);
        btAddCharacterToEpisode1.setRequestFocusEnabled(false);
        btAddCharacterToEpisode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddCharacterToEpisode1ActionPerformed(evt);
            }
        });

        imgCampaign2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/knight.png"))); // NOI18N
        imgCampaign2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 66, 66), 4));

        lblEpisodeDescription1.setForeground(new java.awt.Color(190, 190, 190));
        lblEpisodeDescription1.setText("Description");
        lblEpisodeDescription1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblCharacterClass.setForeground(new java.awt.Color(255, 127, 0));
        lblCharacterClass.setText("Character class");

        lblCharacterName.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        lblCharacterName.setForeground(new java.awt.Color(255, 255, 255));
        lblCharacterName.setText("Character name");

        lblLevel.setForeground(new java.awt.Color(222, 222, 223));
        lblLevel.setText("Level");

        lblCharacterLevel.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        lblCharacterLevel.setForeground(new java.awt.Color(255, 127, 0));
        lblCharacterLevel.setText("1");

        lblCharacterClass1.setForeground(new java.awt.Color(255, 127, 0));
        lblCharacterClass1.setText("Character race");

        lblCharacterClass2.setForeground(new java.awt.Color(255, 127, 0));
        lblCharacterClass2.setText("Character gender");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btAddCharacterToEpisode, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btAddCharacterToEpisode1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imgCampaign2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCharacterName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLevel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCharacterLevel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCharacterClass)
                                    .addComponent(lblCharacterClass1)
                                    .addComponent(lblCharacterClass2))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(lblEpisodeDescription1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgCampaign2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCharacterName)
                            .addComponent(lblCharacterLevel)
                            .addComponent(lblLevel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCharacterClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCharacterClass1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCharacterClass2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEpisodeDescription1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddCharacterToEpisode1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddCharacterToEpisode, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void liMyCharactersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liMyCharactersMouseClicked

    }//GEN-LAST:event_liMyCharactersMouseClicked

    private void tfMyCharactersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMyCharactersKeyPressed

    }//GEN-LAST:event_tfMyCharactersKeyPressed

    private void btSearchMyCharactersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchMyCharactersActionPerformed
        populateList();
    }//GEN-LAST:event_btSearchMyCharactersActionPerformed

    private void btAddCharacterToEpisodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddCharacterToEpisodeActionPerformed
        dispose();
    }//GEN-LAST:event_btAddCharacterToEpisodeActionPerformed

    private void btAddCharacterToEpisode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddCharacterToEpisode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAddCharacterToEpisode1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCharacters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCharacters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCharacters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCharacters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCharacters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddCharacterToEpisode;
    private javax.swing.JButton btAddCharacterToEpisode1;
    private javax.swing.JButton btSearchMyCharacters;
    private javax.swing.JLabel imgCampaign2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCharacterClass;
    private javax.swing.JLabel lblCharacterClass1;
    private javax.swing.JLabel lblCharacterClass2;
    private javax.swing.JLabel lblCharacterLevel;
    private javax.swing.JLabel lblCharacterName;
    private javax.swing.JLabel lblEpisodeDescription1;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JList liMyCharacters;
    private javax.swing.JTextField tfMyCharacters;
    // End of variables declaration//GEN-END:variables
}
