/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import main.RequestManager;
import main.Session;
import model.PlayerCharacter;

/**
 *
 * @author Flo
 */
public class CharacterPanel extends javax.swing.JPanel {

    private CardLayout cl;
    private SelectedCharacter sc;
    private EditCharacter ec;
    private DefaultListModel myCharacters = new DefaultListModel();
    private ArrayList<PlayerCharacter> characters;
    private final String NO_MATCHES = "no matches were found";
    private final String GET_ALL = "ALL";
    private RequestManager rm;

    /**
     * Creates new form Overview
     */
    public CharacterPanel() {
        initComponents();

        cl = (CardLayout) characterContainer.getLayout();

        sc = new SelectedCharacter(cl, characterContainer, ec);
        ec = new EditCharacter(cl, characterContainer);

        characterContainer.add(sc, "selectedCharacter");
        characterContainer.add(ec, "editCharacter");

        liMyCharacters.setModel(myCharacters);
        populateCharacterList();
        try {
            PlayerCharacter ch = (PlayerCharacter) myCharacters.getElementAt(0);
            sc.showSelectedCharacter(ch, ec);
        } catch (Exception ex) {
            ex.toString();
        }
    }

    public void populateCharacterList() {
        rm = new RequestManager();
        characters = rm.getMyCharacters();
        if (characters.isEmpty()) {
            myCharacters.removeAllElements();
            myCharacters.addElement(NO_MATCHES);
        } else {
            myCharacters.removeAllElements();

            for (PlayerCharacter character : characters) {
                myCharacters.addElement(character);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        liMyCharacters = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        tfSearchCharacters = new javax.swing.JTextField();
        btSearchCharacters = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btNewCharacter = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        characterContainer = new javax.swing.JPanel();

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(66, 66, 66));
        jPanel2.setMinimumSize(new java.awt.Dimension(220, 159));

        jScrollPane2.setBackground(new java.awt.Color(66, 66, 66));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(66, 66, 66));

        liMyCharacters.setBackground(new java.awt.Color(66, 66, 66));
        liMyCharacters.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        liMyCharacters.setForeground(new java.awt.Color(204, 204, 204));
        liMyCharacters.setSelectionBackground(new java.awt.Color(255, 127, 0));
        liMyCharacters.setSelectionForeground(new java.awt.Color(40, 40, 40));
        liMyCharacters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liMyCharactersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(liMyCharacters);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        tfSearchCharacters.setBackground(new java.awt.Color(102, 102, 102));
        tfSearchCharacters.setForeground(new java.awt.Color(255, 255, 255));
        tfSearchCharacters.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfSearchCharacters.setBorder(null);
        tfSearchCharacters.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSearchCharactersKeyPressed(evt);
            }
        });

        btSearchCharacters.setBackground(new java.awt.Color(102, 102, 102));
        btSearchCharacters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_icon.png"))); // NOI18N
        btSearchCharacters.setBorder(null);
        btSearchCharacters.setBorderPainted(false);
        btSearchCharacters.setFocusPainted(false);
        btSearchCharacters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchCharactersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(tfSearchCharacters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSearchCharacters, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(tfSearchCharacters, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btSearchCharacters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(66, 66, 66));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All Campaigns" }));
        jComboBox1.setBorder(null);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All Episodes" }));
        jComboBox2.setBorder(null);

        jLabel1.setForeground(new java.awt.Color(255, 127, 0));
        jLabel1.setText("Character filter");

        btNewCharacter.setBackground(new java.awt.Color(40, 40, 40));
        btNewCharacter.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btNewCharacter.setForeground(new java.awt.Color(255, 255, 255));
        btNewCharacter.setText("Create a new Character");
        btNewCharacter.setBorder(null);
        btNewCharacter.setBorderPainted(false);
        btNewCharacter.setRequestFocusEnabled(false);
        btNewCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewCharacterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(btNewCharacter, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btNewCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(jPanel2, gridBagConstraints);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        characterContainer.setBackground(new java.awt.Color(40, 40, 40));
        characterContainer.setMaximumSize(new java.awt.Dimension(400, 600));
        characterContainer.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(characterContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(characterContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jPanel3, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void liMyCharactersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liMyCharactersMouseClicked
        PlayerCharacter ch = (PlayerCharacter) myCharacters.getElementAt(
                liMyCharacters.getSelectedIndex());
        sc.showSelectedCharacter(ch, ec);
    }//GEN-LAST:event_liMyCharactersMouseClicked

    private void tfSearchCharactersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchCharactersKeyPressed

    }//GEN-LAST:event_tfSearchCharactersKeyPressed

    private void btSearchCharactersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchCharactersActionPerformed
        populateCharacterList();
    }//GEN-LAST:event_btSearchCharactersActionPerformed

    private void btNewCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewCharacterActionPerformed
        cl.show(characterContainer, "editCharacter");
        ec.setEmptyFields();
    }//GEN-LAST:event_btNewCharacterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNewCharacter;
    private javax.swing.JButton btSearchCharacters;
    private javax.swing.JPanel characterContainer;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList liMyCharacters;
    private javax.swing.JTextField tfSearchCharacters;
    // End of variables declaration//GEN-END:variables
}
