/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import main.RequestManager;
import main.Session;
import model.PlayerCharacter;

/**
 *
 * @author Florentijn
 */
public class EditCharacter extends javax.swing.JPanel {

    private final String EMPTY = "";
    private CardLayout cl;
    private JPanel characterContainer;
    private PlayerCharacter character;
    private RequestManager rm;

    /**
     * Creates new form SelectedCharacter
     */
    public EditCharacter(CardLayout cl, JPanel characterContainer) {
        this.cl = cl;
        this.characterContainer = characterContainer;
        initComponents();
        InitiateLevelBox();
    }

    public void setEmptyFields() {
        tfCharacterName.setText(EMPTY);
        tfClass.setText(EMPTY);
        tfRace.setText(EMPTY);
        cbGender.setSelectedIndex(0);
        cbLevel.setSelectedIndex(0);
        tpDescription.setText(EMPTY);
        countChars();
    }

    public void setCharacter(PlayerCharacter character) {
        this.character = character;
        tfCharacterName.setText(character.getName());
        tfClass.setText(character.getClassType());
        tfRace.setText(character.getRace());
        cbGender.setSelectedItem(character.getGender());
        cbLevel.setSelectedIndex(character.getLevel() - 1);
        tpDescription.setText(character.getDescription());
        countChars();
    }

    public void InitiateLevelBox() {
        for (int i = 1; i <= 30; i++) {
            cbLevel.addItem(i);
        }
    }

    public void countChars() {
        if (tpDescription.getText().length() == 0) {
            lblWordCount.setText(EMPTY);
        }
        if (tpDescription.getText().length() > 600) {
            lblWordCount.setText("<html><font color='red'>"
                    + tpDescription.getText().length()
                    + " / 600 max. characters </font></html>");
        } else {
            lblWordCount.setText(tpDescription.getText().length() + " / 600 max. characters");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        imgCampaign2 = new javax.swing.JLabel();
        lblRace = new javax.swing.JLabel();
        btCancel = new javax.swing.JButton();
        lblGender = new javax.swing.JLabel();
        tfClass = new javax.swing.JTextField();
        tfRace = new javax.swing.JTextField();
        cbGender = new javax.swing.JComboBox();
        lblDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpDescription = new javax.swing.JTextPane();
        tfCharacterName = new javax.swing.JTextField();
        cbLevel = new javax.swing.JComboBox();
        btCommit = new javax.swing.JButton();
        lblWordCount = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(40, 40, 40));
        jPanel6.setMaximumSize(new java.awt.Dimension(400, 600));

        lblName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 127, 0));
        lblName.setText("Character name");

        lblClass.setForeground(new java.awt.Color(255, 127, 0));
        lblClass.setText("Class");

        lblLevel.setForeground(new java.awt.Color(255, 127, 0));
        lblLevel.setText("Level");

        imgCampaign2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/knight.png"))); // NOI18N
        imgCampaign2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 66, 66), 4));

        lblRace.setForeground(new java.awt.Color(255, 127, 0));
        lblRace.setText("Race");

        btCancel.setBackground(new java.awt.Color(66, 66, 66));
        btCancel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btCancel.setForeground(new java.awt.Color(255, 255, 255));
        btCancel.setText("Cancel");
        btCancel.setBorder(null);
        btCancel.setBorderPainted(false);
        btCancel.setRequestFocusEnabled(false);
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        lblGender.setBackground(new java.awt.Color(204, 204, 204));
        lblGender.setForeground(new java.awt.Color(255, 127, 0));
        lblGender.setText("Gender");

        tfClass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tfRace.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        cbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        cbGender.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblDescription.setBackground(new java.awt.Color(204, 204, 204));
        lblDescription.setForeground(new java.awt.Color(204, 204, 204));
        lblDescription.setText("Description");

        jScrollPane1.setBorder(null);

        tpDescription.setBackground(new java.awt.Color(102, 102, 102));
        tpDescription.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tpDescription.setForeground(new java.awt.Color(255, 255, 255));
        tpDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tpDescriptionKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tpDescription);

        tfCharacterName.setText("jTextField3");
        tfCharacterName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btCommit.setBackground(new java.awt.Color(66, 66, 66));
        btCommit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btCommit.setForeground(new java.awt.Color(255, 255, 255));
        btCommit.setText("Commit Changes");
        btCommit.setBorder(null);
        btCommit.setBorderPainted(false);
        btCommit.setRequestFocusEnabled(false);
        btCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCommitActionPerformed(evt);
            }
        });

        lblWordCount.setBackground(new java.awt.Color(204, 204, 204));
        lblWordCount.setForeground(new java.awt.Color(204, 204, 204));
        lblWordCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWordCount.setText("Word Count");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgCampaign2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRace, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGender))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfRace)
                            .addComponent(tfClass)
                            .addComponent(cbGender, 0, 104, Short.MAX_VALUE)))
                    .addComponent(btCommit, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWordCount))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addGap(6, 6, 6)
                        .addComponent(tfCharacterName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                        .addComponent(lblLevel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(cbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCharacterName)
                            .addComponent(lblLevel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescription)
                            .addComponent(lblWordCount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(imgCampaign2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClass)
                            .addComponent(tfClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfRace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRace))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGender)
                            .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCommit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        cl.show(characterContainer, "selectedCharacter");
    }//GEN-LAST:event_btCancelActionPerformed

    private void btCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCommitActionPerformed
        if (tpDescription.getText().length() > 600) {
            JOptionPane.showMessageDialog(null, "description is too long", "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            rm = new RequestManager();
            character = new PlayerCharacter(
                    cbLevel.getSelectedIndex() + 1,
                    Session.getCurrentUserId(),
                    tfCharacterName.getText().trim(),
                    cbGender.getSelectedItem().toString(),
                    tfClass.getText().trim(),
                    tfRace.getText().trim(),
                    tpDescription.getText().trim());
            if (rm.createCharacter(character)) {
                JOptionPane.showMessageDialog(null, "Character '" + character.getName()
                        + "' succesfully created!", "Success!",
                        JOptionPane.OK_OPTION);
                cl.show(characterContainer, "selectedCharacter");
            }
        }
    }//GEN-LAST:event_btCommitActionPerformed

    private void tpDescriptionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpDescriptionKeyReleased
        countChars();
    }//GEN-LAST:event_tpDescriptionKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btCommit;
    private javax.swing.JComboBox cbGender;
    private javax.swing.JComboBox cbLevel;
    private javax.swing.JLabel imgCampaign2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRace;
    private javax.swing.JLabel lblWordCount;
    private javax.swing.JTextField tfCharacterName;
    private javax.swing.JTextField tfClass;
    private javax.swing.JTextField tfRace;
    private javax.swing.JTextPane tpDescription;
    // End of variables declaration//GEN-END:variables
}
