/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.io.*;
import java.net.*;
import javax.swing.AbstractButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import main.*;

/**
 *
 * @author Flo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
        for (int i = 0; i < cbServers.getComponentCount(); i++) {
            if (cbServers.getComponent(i) instanceof JComponent) {
                ((JComponent) cbServers.getComponent(i)).setBorder(new EmptyBorder(0, 0,0,0));
            }
            if (cbServers.getComponent(i) instanceof AbstractButton) {
                ((AbstractButton) cbServers.getComponent(i)).setBorderPainted(false);
            }
        }
    }
    
    public void doLogin() throws IOException {
        String username = tfUsername.getText();
        String password = tfPassword.getText();
        
        Socket connection = new Socket(cbServers.getSelectedItem().toString().trim(), 1226);
        
        // Creates output to send to server
        OutputStream toServer = connection.getOutputStream();
        PrintStream ps = new PrintStream(toServer, true); // Second param: auto-flush on write = true
        
        // Item to send
        ps.println((username + ":" + password + ":login"));
        
        InputStream in = connection.getInputStream();
        BufferedReader fromServer = new BufferedReader(new InputStreamReader(in));
        String line = fromServer.readLine();
        
        if(line.equals("Login succesful!")){
            Session.setCurrentUsername(username);
            Session.setCurrentPassword(password);
            Session.setCurrentServerIp(cbServers.getSelectedItem().toString().trim());
            Session.setCurrentServerPort(1226);
            
            Main.displayOverview();
            
            System.out.println(line);
            connection.close();
            dispose();
        } else if(line.equals("WAT PROBEER JE ME TE HACKEN BITCH!?")) {
            JOptionPane.showMessageDialog(null, line, "Error",
                                JOptionPane.ERROR_MESSAGE);
            connection.close();
        } else {
            JOptionPane.showMessageDialog(null, "Username/Password is incorrect", "Error",
                                JOptionPane.ERROR_MESSAGE);
            System.out.println("Jammer joh..");
            connection.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        btClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbServers = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getToolkit().getImage(getClass().getResource("/img/dock_icon.png")));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 127, 0));
        jLabel4.setText("Username");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 127, 0));
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 127, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Adventure Planner");

        tfUsername.setBackground(new java.awt.Color(102, 102, 102));
        tfUsername.setForeground(new java.awt.Color(204, 204, 204));
        tfUsername.setBorder(null);

        tfPassword.setBackground(new java.awt.Color(102, 102, 102));
        tfPassword.setForeground(new java.awt.Color(204, 204, 204));
        tfPassword.setBorder(null);

        btLogin.setBackground(new java.awt.Color(102, 102, 102));
        btLogin.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btLogin.setForeground(new java.awt.Color(255, 255, 255));
        btLogin.setText("Login");
        btLogin.setBorder(null);
        btLogin.setBorderPainted(false);
        btLogin.setFocusPainted(false);
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        btClose.setBackground(new java.awt.Color(102, 102, 102));
        btClose.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btClose.setForeground(new java.awt.Color(255, 255, 255));
        btClose.setText("Close");
        btClose.setBorder(null);
        btClose.setBorderPainted(false);
        btClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btClose.setFocusPainted(false);
        btClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 127, 0));
        jLabel1.setText("Server Address");

        cbServers.setBackground(new java.awt.Color(102, 102, 102));
        cbServers.setEditable(true);
        cbServers.setForeground(new java.awt.Color(204, 204, 204));
        cbServers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "localhost", "83.160.96.155" }));
        cbServers.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btClose, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfUsername)
                            .addComponent(cbServers, 0, 218, Short.MAX_VALUE)
                            .addComponent(tfPassword))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbServers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(btClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btCloseActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        if(tfUsername.getText().trim().equals("") || tfPassword.getText().trim().equals(""))
            JOptionPane.showMessageDialog(null, "Please enter a username and password..", "Error",
                                    JOptionPane.ERROR_MESSAGE);
        else{
            try {
                doLogin();
            } catch(IOException e) {
                JOptionPane.showMessageDialog(null, e.toString(), "Error",
                                JOptionPane.ERROR_MESSAGE);
                System.out.println("aapje");
            }
        }
    }//GEN-LAST:event_btLoginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClose;
    private javax.swing.JButton btLogin;
    private javax.swing.JComboBox cbServers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}