/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.CardLayout;
import main.*;

/**
 *
 * @author Flo
 */
public class Overview extends javax.swing.JFrame {
    
    private CardLayout cl;
    /**
     * Creates new form Overview
     */
    public Overview() {
        initComponents();
        
        HomePanel hp = new HomePanel();
        CharacterPanel cp = new CharacterPanel();
        
        mainContainer.add(hp, "home");
        mainContainer.add(cp, "character");
        
        cl = (CardLayout)mainContainer.getLayout();
        
        tempSpacerMenu.setEnabled(false);
        overviewMenu.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainer = new javax.swing.JPanel();
        overviewMenu = new javax.swing.JMenuBar();
        viewMenu = new javax.swing.JMenu();
        homeMenuItem = new javax.swing.JMenuItem();
        homeMenuItem1 = new javax.swing.JMenuItem();
        tempSpacerMenu = new javax.swing.JMenu();
        settingsMenu = new javax.swing.JMenu();
        miOptions = new javax.swing.JMenuItem();
        accountMenu = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        miChangePassword = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adventure Planner");
        setIconImage(getToolkit().getImage(getClass().getResource("/img/account_icon.png")));
        setMinimumSize(new java.awt.Dimension(953, 499));

        mainContainer.setLayout(new java.awt.CardLayout());

        overviewMenu.setBackground(new java.awt.Color(30, 30, 30));
        overviewMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        overviewMenu.setForeground(new java.awt.Color(51, 51, 51));
        overviewMenu.setBorderPainted(false);
        overviewMenu.setMargin(new java.awt.Insets(40, 40, 40, 40));
        overviewMenu.setMinimumSize(new java.awt.Dimension(0, 50));
        overviewMenu.setName(""); // NOI18N
        overviewMenu.setPreferredSize(new java.awt.Dimension(54, 30));

        viewMenu.setBackground(new java.awt.Color(30, 30, 30));
        viewMenu.setForeground(new java.awt.Color(255, 127, 0));
        viewMenu.setText("View");
        viewMenu.setActionCommand("VIEW");
        viewMenu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        homeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_HOME, 0));
        homeMenuItem.setBackground(new java.awt.Color(30, 30, 30));
        homeMenuItem.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        homeMenuItem.setForeground(new java.awt.Color(255, 127, 0));
        homeMenuItem.setText("Home");
        homeMenuItem.setBorder(null);
        homeMenuItem.setPreferredSize(new java.awt.Dimension(150, 26));
        homeMenuItem.setRequestFocusEnabled(false);
        homeMenuItem.setSelected(true);
        homeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeMenuItemActionPerformed(evt);
            }
        });
        viewMenu.add(homeMenuItem);

        homeMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        homeMenuItem1.setBackground(new java.awt.Color(30, 30, 30));
        homeMenuItem1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        homeMenuItem1.setForeground(new java.awt.Color(255, 127, 0));
        homeMenuItem1.setText("Characters");
        homeMenuItem1.setBorder(null);
        homeMenuItem1.setPreferredSize(new java.awt.Dimension(150, 26));
        homeMenuItem1.setRequestFocusEnabled(false);
        homeMenuItem1.setSelected(true);
        homeMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeMenuItem1ActionPerformed(evt);
            }
        });
        viewMenu.add(homeMenuItem1);

        overviewMenu.add(viewMenu);

        tempSpacerMenu.setBackground(new java.awt.Color(30, 30, 30));
        tempSpacerMenu.setForeground(new java.awt.Color(255, 127, 0));
        tempSpacerMenu.setFocusable(false);
        tempSpacerMenu.setMinimumSize(new java.awt.Dimension(300, 0));
        tempSpacerMenu.setPreferredSize(new java.awt.Dimension(300, 0));
        overviewMenu.add(tempSpacerMenu);

        settingsMenu.setBackground(new java.awt.Color(30, 30, 30));
        settingsMenu.setBorder(null);
        settingsMenu.setForeground(new java.awt.Color(255, 127, 0));
        settingsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/settings_icon.png"))); // NOI18N
        settingsMenu.setContentAreaFilled(false);
        settingsMenu.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        settingsMenu.setMinimumSize(new java.awt.Dimension(40, 40));
        settingsMenu.setPreferredSize(new java.awt.Dimension(30, 40));

        miOptions.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        miOptions.setBackground(new java.awt.Color(30, 30, 30));
        miOptions.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        miOptions.setForeground(new java.awt.Color(255, 127, 0));
        miOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/settings_icon.png"))); // NOI18N
        miOptions.setText("Options");
        miOptions.setBorder(null);
        miOptions.setPreferredSize(new java.awt.Dimension(150, 42));
        miOptions.setRequestFocusEnabled(false);
        miOptions.setSelected(true);
        miOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOptionsActionPerformed(evt);
            }
        });
        settingsMenu.add(miOptions);

        overviewMenu.add(settingsMenu);

        accountMenu.setBackground(new java.awt.Color(30, 30, 30));
        accountMenu.setBorder(null);
        accountMenu.setForeground(new java.awt.Color(255, 127, 0));
        accountMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/account_icon.png"))); // NOI18N
        accountMenu.setMinimumSize(new java.awt.Dimension(30, 40));
        accountMenu.setPreferredSize(new java.awt.Dimension(30, 40));

        miLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        miLogout.setBackground(new java.awt.Color(30, 30, 30));
        miLogout.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        miLogout.setForeground(new java.awt.Color(255, 127, 0));
        miLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout_icon.png"))); // NOI18N
        miLogout.setText("Logout");
        miLogout.setBorder(null);
        miLogout.setPreferredSize(new java.awt.Dimension(150, 42));
        miLogout.setRequestFocusEnabled(false);
        miLogout.setSelected(true);
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        accountMenu.add(miLogout);

        miChangePassword.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.CTRL_MASK));
        miChangePassword.setBackground(new java.awt.Color(30, 30, 30));
        miChangePassword.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        miChangePassword.setForeground(new java.awt.Color(255, 127, 0));
        miChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password_icon.png"))); // NOI18N
        miChangePassword.setText("Change password");
        miChangePassword.setBorder(null);
        miChangePassword.setMinimumSize(new java.awt.Dimension(200, 42));
        miChangePassword.setPreferredSize(new java.awt.Dimension(200, 42));
        miChangePassword.setRequestFocusEnabled(false);
        miChangePassword.setSelected(true);
        miChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miChangePasswordActionPerformed(evt);
            }
        });
        accountMenu.add(miChangePassword);

        overviewMenu.add(accountMenu);

        setJMenuBar(overviewMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        Session.setCurrentUsername(null);
        Session.setCurrentServerIp(null);
        Session.setCurrentServerPort(0);
        Session.setCurrentPassword(null);

        dispose();
        Main.displayLogin();
    }//GEN-LAST:event_miLogoutActionPerformed

    private void miChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miChangePasswordActionPerformed
        Main.displayChangePassword();
    }//GEN-LAST:event_miChangePasswordActionPerformed

    private void miOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miOptionsActionPerformed

    private void homeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeMenuItemActionPerformed
        cl.show(mainContainer, "home");
    }//GEN-LAST:event_homeMenuItemActionPerformed

    private void homeMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeMenuItem1ActionPerformed
        cl.show(mainContainer, "character");
    }//GEN-LAST:event_homeMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu accountMenu;
    private javax.swing.JMenuItem homeMenuItem;
    private javax.swing.JMenuItem homeMenuItem1;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JMenuItem miChangePassword;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miOptions;
    private javax.swing.JMenuBar overviewMenu;
    private javax.swing.JMenu settingsMenu;
    private javax.swing.JMenu tempSpacerMenu;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
}