/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import javax.swing.JPanel;
import main.RequestManager;
import model.PlayerCharacter;

/**
 *
 * @author Florentijn
 */
public class SelectedCharacter extends javax.swing.JPanel {

    private CardLayout cl;
    private JPanel characterContainer;
    private EditCharacter ec;
    private PlayerCharacter character;
    private RequestManager rm;

    /**
     * Creates new form SelectedCharacter
     */
    public SelectedCharacter(CardLayout cl, JPanel characterContainer,
            EditCharacter editCharacter) {
        this.ec = editCharacter;
        this.cl = cl;
        this.characterContainer = characterContainer;
        initComponents();
    }

    public void showSelectedCharacter(PlayerCharacter character, EditCharacter ec) {
        this.character = character;
        lblName.setText(character.getName());
        lblClass.setText(character.getClassType());
        lblCharacterLevel.setText(character.getLevel().toString());
        lblRace.setText(character.getRace());
        lblGender.setText(character.getGender());
        lblCharacterDescription.setText("<html>" + character.getDescription() + "</html>");
        ec.setCharacter(character);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblCharacterDescription = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        lblCharacterLevel = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        imgCampaign2 = new javax.swing.JLabel();
        lblRace = new javax.swing.JLabel();
        btEditCharacter = new javax.swing.JButton();
        lblGender = new javax.swing.JLabel();
        btDeleteCharacter = new javax.swing.JButton();

        jPanel6.setBackground(new java.awt.Color(40, 40, 40));
        jPanel6.setMaximumSize(new java.awt.Dimension(400, 600));

        lblName.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Character name");

        lblCharacterDescription.setForeground(new java.awt.Color(190, 190, 190));
        lblCharacterDescription.setText("Description");
        lblCharacterDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblCharacterDescription.setMaximumSize(new java.awt.Dimension(413, 14));

        lblClass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblClass.setForeground(new java.awt.Color(255, 127, 0));
        lblClass.setText("Class");

        lblCharacterLevel.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        lblCharacterLevel.setForeground(new java.awt.Color(255, 127, 0));
        lblCharacterLevel.setText("1");

        lblLevel.setForeground(new java.awt.Color(222, 222, 223));
        lblLevel.setText("Level");

        imgCampaign2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/knight.png"))); // NOI18N
        imgCampaign2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 66, 66), 4));

        lblRace.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRace.setForeground(new java.awt.Color(255, 127, 0));
        lblRace.setText("Race");

        btEditCharacter.setBackground(new java.awt.Color(66, 66, 66));
        btEditCharacter.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btEditCharacter.setForeground(new java.awt.Color(255, 255, 255));
        btEditCharacter.setText("Edit Character");
        btEditCharacter.setBorder(null);
        btEditCharacter.setBorderPainted(false);
        btEditCharacter.setRequestFocusEnabled(false);
        btEditCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditCharacterActionPerformed(evt);
            }
        });

        lblGender.setBackground(new java.awt.Color(204, 204, 204));
        lblGender.setForeground(new java.awt.Color(204, 204, 204));
        lblGender.setText("Gender");

        btDeleteCharacter.setBackground(new java.awt.Color(66, 66, 66));
        btDeleteCharacter.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btDeleteCharacter.setForeground(new java.awt.Color(255, 255, 255));
        btDeleteCharacter.setText("Delete Character");
        btDeleteCharacter.setBorder(null);
        btDeleteCharacter.setBorderPainted(false);
        btDeleteCharacter.setRequestFocusEnabled(false);
        btDeleteCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteCharacterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btEditCharacter, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(imgCampaign2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGender)
                    .addComponent(btDeleteCharacter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                        .addComponent(lblLevel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCharacterLevel))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblCharacterDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(imgCampaign2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(btDeleteCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEditCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(lblCharacterLevel)
                            .addComponent(lblLevel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCharacterDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btEditCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditCharacterActionPerformed
        cl.show(characterContainer, "editCharacter");
    }//GEN-LAST:event_btEditCharacterActionPerformed

    private void btDeleteCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteCharacterActionPerformed
        rm = new RequestManager();
//        System.out.println(character.getId());
        rm.deleteCharacter(character.getId());
    }//GEN-LAST:event_btDeleteCharacterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDeleteCharacter;
    private javax.swing.JButton btEditCharacter;
    private javax.swing.JLabel imgCampaign2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCharacterDescription;
    private javax.swing.JLabel lblCharacterLevel;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRace;
    // End of variables declaration//GEN-END:variables
}